# \copyright 2017 Zorxx Software, All Rights Reserved
# \license This file is released under the MIT License. See the LICENSE file for details.
# \brief Recipe for ESP8266 SDK Extras 

include ../../../include/mb.inc

PACKAGE_NAME := esp8266_sdk_extras

# Download information
$(PACKAGE_NAME)_SOURCE := "https://github.com/esp8266/esp8266-wiki.git"
$(PACKAGE_NAME)_SOURCE_METHOD := git

SRCDIR := $(PACKAGE_NAME)_source

EXTERNAL_TARGETS += $(PACKAGE_NAME)

include $(INCLUDE_DIR)/ext.inc
include $(INCLUDE_DIR)/dir.inc

# vim: syntax=make tabstop=4 noexpandtab
