# \copyright 2015 Zorxx Software, All Rights Reserved.
# \license This file is released under the MIT License. See the LICENSE file for details.
# \brief Lean and mean UART library

include ../../include/top.inc

LIB_NAME = uart_lite
SRC = $(wildcard *.c)

all: library
clean: library_clean

include ../../include/bottom.inc
