language: c
script: make
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev libusb-1.0.0-dev
env:
    matrix:
        - MB_TARGET=xtensa_nodemcu_arduino
        - MB_TARGET=xtensa_esp12f_arduino
        - MB_TARGET=xtensa_nodemcu
        - MB_TARGET=xtensa_esp12f
        - MB_TARGET=avr_nano_arduino
        - MB_TARGET=arm_bluepill_arduino
        - MB_TARGET=arm_bluepill_libopencm3
        - MB_TARGET=arm_stm32f103c_arduino
