language: c
script: make
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev libusb-1.0.0-dev
matrix:
    include:
        - env: MB_TARGET=xtensa_nodemcu_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=xtensa_esp12f_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=xtensa_nodemcu
        - env: MB_TARGET=xtensa_esp12f
        - env: MB_TARGET=xtensa_huzzah
        - env: MB_TARGET=avr_nano_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_bluepill_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_bluepill_libopencm3
        - env: MB_TARGET=arm_stm32f103c_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_stm32f4_arduino;TEST_APP=app/arduino/blink
script:
    - sh -c "if [ '${TEST_APP}' != '' ]; then make -C ${TEST_APP}; fi"
    - sh -c "if [ '${TEST_APP}' = '' ]; then make; fi"
