language: c
script: make
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev libusb-1.0.0-dev
  - sudo apt-get install -y gperf texinfo help2man flex bison
matrix:
    include:
        - env: MB_TARGET=xtensa_esp07_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=xtensa_nodemcu_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=xtensa_esp12f_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=xtensa_nodemcu;TEST_APP=app/esp8266/hello_world
        - env: MB_TARGET=xtensa_esp12f;TEST_APP=app/esp8266/hello_world
        - env: MB_TARGET=xtensa_huzzah;TEST_APP=app/esp8266/hello_world
        - env: MB_TARGET=avr_nano_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_bluepill_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_bluepill_libopencm3
        - env: MB_TARGET=arm_stm32f103c_arduino;TEST_APP=app/arduino/blink
        - env: MB_TARGET=arm_stm32f4_arduino;TEST_APP=app/arduino/blink
script:
    - unset CC;make all
    - sh -c "if [ '${TEST_APP}' != '' ]; then make -C ${TEST_APP}; fi"
