# \copyright 2015 Zorxx Software, All Rights Reserved.
# \license This file is released under the MIT License. See the LICENSE file for details.
# \brief Hello World application

include ../../top.inc

APP_NAME = hello_world
SRC = $(wildcard *.c)
LIBS = gcc phy pp net80211 lwip wpa main crypto uart_lite

all: app
clean: app_clean

include ../../bottom.inc
