void _close_r() {}
void _execve_r() {}
void _fcntl_r() {}
void _fork_r() {}
void _fstat_r() {}
void _getpid_r() {}
void _isatty_r() {}
void _kill_r() {} 
void _link_r() {}
void _lseek_r() {}
void _mkdir_r() {}
void _open_r() {}
void _read_r() {}
void _rename_r() {}
void _sbrk_r() {}
void _stat_r() {}
void _times_r() {}
void _unlink_r() {}
void _wait_r() {}
void _write_r() {}
void _gettimeofday_r() {}
