# \copyright 2015 Zorxx Software, All Rights Reserved
# \license This file is released under the MIT License. See the LICENSE file for details.
# \brief Recipe for ESP8266 sysgcc toolchain

include ../../../include/mb.inc

all:
	@$(ECHO) "TODO: Validate toolchain installation"
clean:

# vim: syntax=make tabstop=4 noexpandtab
