# \copyright 2017 Zorxx Software, All Rights Reserved
# \license This file is released under the MIT License. See the LICENSE file for details.
# \brief Recipe for Adafruit sensor library package

include ../../../include/mb.inc

PACKAGE_NAME := Adafruit_Sensor

# Download information
$(PACKAGE_NAME)_SOURCE := "https://github.com/adafruit/Adafruit_Sensor.git"
$(PACKAGE_NAME)_SOURCE_METHOD := git

EXTERNAL_TARGETS += $(PACKAGE_NAME)

include $(INCLUDE_DIR)/ext.inc
include $(INCLUDE_DIR)/dir.inc

# vim: syntax=make tabstop=4 noexpandtab
